apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: simple-jwt-api
  template:
    metadata:
      labels: { app: simple-jwt-api }
    spec:
      containers:
        [
          {
            name: simple-jwt-api,
            image: "223280877749.dkr.ecr.us-east-2.amazonaws.com/udaci-ecrdo-1eztz6umioq13:deploy-flask-to-kubernetes.master..2020-04-24.11.28.40.654e82d5",
            securityContext:
              {
                privileged: false,
                readOnlyRootFilesystem: false,
                allowPrivilegeEscalation: false,
              },
            ports: [{ containerPort: 8080 }],
          },
        ]
